import { TagEntity } from '@app/entities';
import { Injectable } from '@nestjs/common';
import {
  TagResponseDto,
  TagStatsDto,
  TagUsageStatsDto,
  TagWithPaginationResponseDto,
} from './models';

@Injectable()
export class TagMapper {
  /**
   * Convert TagEntity to TagResponseDto
   */
  toResponseDto(tag: TagEntity): TagResponseDto {
    return {
      id: tag.id,
      name: tag.name,
      displayName: tag.getDisplayName(),
      description: tag.description,
      color: tag.color,
      category: tag.category,
      usageCount: tag.usageCount,
      isActive: tag.isActive,
      isSystem: tag.isSystem,
      authorId: tag.user?.id,
      createdAt: tag.createAt!,
      updatedAt: tag.updateAt!,
    };
  }

  /**
   * Convert array of TagEntity to array of TagResponseDto
   */
  toResponseDtoArray(tags: TagEntity[]): TagResponseDto[] {
    return tags.map((tag) => this.toResponseDto(tag));
  }

  /**
   * Convert paginated tags to TagWithPaginationResponseDto
   */
  toPaginationResponseDto(
    tags: TagEntity[],
    total: number,
    offset: number,
    limit: number,
  ): TagWithPaginationResponseDto {
    return {
      tags: this.toResponseDtoArray(tags),
      total,
      offset,
      limit,
      hasMore: offset + limit < total,
    };
  }

  /**
   * Convert tag stats to TagStatsDto
   */
  toStatsDto(stats: {
    total: number;
    active: number;
    inactive: number;
    unused: number;
    categories: { category: string; count: number }[];
    totalUsage: number;
  }): TagStatsDto {
    return {
      total: stats.total,
      active: stats.active,
      inactive: stats.inactive,
      unused: stats.unused,
      totalUsage: stats.totalUsage,
      categories: stats.categories,
    };
  }

  /**
   * Convert tag usage stats to TagUsageStatsDto
   */
  toUsageStatsDto(stats: {
    totalAssignments: number;
    autoGenerated: number;
    manuallyAdded: number;
    averageTagsPerBookmark: number;
    mostUsedTags: { tagId: string; tagName: string; count: number }[];
  }): TagUsageStatsDto {
    return {
      totalAssignments: stats.totalAssignments,
      autoGenerated: stats.autoGenerated,
      manuallyAdded: stats.manuallyAdded,
      averageTagsPerBookmark: stats.averageTagsPerBookmark,
      mostUsedTags: stats.mostUsedTags,
    };
  }

  /**
   * Convert TagEntity to summary object
   */
  toSummary(tag: TagEntity): {
    id: string;
    name: string;
    displayName: string;
    color?: string;
    category?: string;
    usageCount: number;
    isActive: boolean;
  } {
    return {
      id: tag.id,
      name: tag.name,
      displayName: tag.getDisplayName(),
      color: tag.color,
      category: tag.category,
      usageCount: tag.usageCount,
      isActive: tag.isActive,
    };
  }

  /**
   * Convert array of TagEntity to summary array
   */
  toSummaryArray(tags: TagEntity[]): Array<{
    id: string;
    name: string;
    displayName: string;
    color?: string;
    category?: string;
    usageCount: number;
    isActive: boolean;
  }> {
    return tags.map((tag) => this.toSummary(tag));
  }

  /**
   * Convert TagEntity to autocomplete suggestion
   */
  toAutocompleteSuggestion(tag: TagEntity): {
    id: string;
    name: string;
    displayName: string;
    color?: string;
    usageCount: number;
  } {
    return {
      id: tag.id,
      name: tag.name,
      displayName: tag.getDisplayName(),
      color: tag.color,
      usageCount: tag.usageCount,
    };
  }

  /**
   * Convert array of TagEntity to autocomplete suggestions
   */
  toAutocompleteSuggestions(tags: TagEntity[]): Array<{
    id: string;
    name: string;
    displayName: string;
    color?: string;
    usageCount: number;
  }> {
    return tags.map((tag) => this.toAutocompleteSuggestion(tag));
  }
}
