import { FindOptions } from '@mikro-orm/core';
import { EntityRepository } from '@mikro-orm/postgresql';
import { BookmarkTagEntity } from '../entities/bookmark-tag.entity';

type FindBookmarkTagOptions = FindOptions<
  BookmarkTagEntity,
  'bookmark' | 'tag' | 'addedBy',
  '*',
  never
>;

export class BookmarkTagRepository extends EntityRepository<BookmarkTagEntity> {
  /**
   * Find bookmark tags by bookmark ID
   */
  async findByBookmarkId(
    bookmarkId: string,
    options?: FindBookmarkTagOptions,
  ): Promise<BookmarkTagEntity[]> {
    return this.find(
      {
        bookmark: { id: bookmarkId },
        deleteFlag: false,
      },
      {
        populate: ['tag', 'addedBy'],
        orderBy: { createAt: 'ASC' },
        ...options,
      },
    );
  }

  /**
   * Find bookmark tags by tag ID
   */
  async findByTagId(
    tagId: string,
    options?: FindBookmarkTagOptions,
  ): Promise<BookmarkTagEntity[]> {
    return this.find(
      {
        tag: { id: tagId },
        deleteFlag: false,
      },
      {
        populate: ['bookmark', 'addedBy'],
        orderBy: { createAt: 'DESC' },
        ...options,
      },
    );
  }

  /**
   * Find bookmark tag by bookmark and tag
   */
  async findByBookmarkAndTag(
    bookmarkId: string,
    tagId: string,
    options?: FindBookmarkTagOptions,
  ): Promise<BookmarkTagEntity | null> {
    return this.findOne(
      {
        bookmark: { id: bookmarkId },
        tag: { id: tagId },
        deleteFlag: false,
      },
      {
        populate: ['tag', 'bookmark', 'addedBy'],
        ...options,
      },
    );
  }

  /**
   * Find bookmark tags by user
   */
  async findByUserId(
    userId: string,
    options?: FindBookmarkTagOptions,
  ): Promise<BookmarkTagEntity[]> {
    return this.find(
      {
        addedBy: { id: userId },
        deleteFlag: false,
      },
      {
        populate: ['bookmark', 'tag'],
        orderBy: { createAt: 'DESC' },
        ...options,
      },
    );
  }

  /**
   * Find auto-generated bookmark tags
   */
  async findAutoGenerated(
    userId: string,
    minConfidence: number = 0.7,
    options?: FindBookmarkTagOptions,
  ): Promise<BookmarkTagEntity[]> {
    return this.find(
      {
        addedBy: { id: userId },
        isAutoGenerated: true,
        confidence: { $gte: minConfidence },
        deleteFlag: false,
      },
      {
        populate: ['bookmark', 'tag'],
        orderBy: { confidence: 'DESC', createAt: 'DESC' },
        ...options,
      },
    );
  }

  /**
   * Count bookmarks for a tag
   */
  async countByTagId(tagId: string): Promise<number> {
    return this.count({
      tag: { id: tagId },
      deleteFlag: false,
    });
  }

  /**
   * Count tags for a bookmark
   */
  async countByBookmarkId(bookmarkId: string): Promise<number> {
    return this.count({
      bookmark: { id: bookmarkId },
      deleteFlag: false,
    });
  }

  /**
   * Get tag usage statistics
   */
  async getTagUsageStats(userId: string): Promise<{
    totalAssignments: number;
    autoGenerated: number;
    manuallyAdded: number;
    averageTagsPerBookmark: number;
    mostUsedTags: { tagId: string; tagName: string; count: number }[];
  }> {
    const [totalAssignments, autoGenerated, manuallyAdded] = await Promise.all([
      this.count({
        addedBy: { id: userId },
        deleteFlag: false,
      }),
      this.count({
        addedBy: { id: userId },
        isAutoGenerated: true,
        deleteFlag: false,
      }),
      this.count({
        addedBy: { id: userId },
        isAutoGenerated: false,
        deleteFlag: false,
      }),
    ]);

    // Get average tags per bookmark
    const avgResult = await this.getEntityManager()
      .getConnection()
      .execute(
        `SELECT AVG(tag_count) as avg_tags
         FROM (
           SELECT COUNT(*) as tag_count
           FROM bookmark_tag_entity bt
           JOIN bookmark_entity b ON bt.bookmark_id = b.id
           WHERE b.user_id = ? AND bt.delete_flag = false AND b.delete_flag = false
           GROUP BY bt.bookmark_id
         ) subquery`,
        [userId],
      );
    const averageTagsPerBookmark = parseFloat(avgResult[0]?.avg_tags || '0');

    // Get most used tags
    const mostUsedResult = await this.getEntityManager()
      .getConnection()
      .execute(
        `SELECT t.id as tag_id, t.name as tag_name, COUNT(*) as count
         FROM bookmark_tag_entity bt
         JOIN tag_entity t ON bt.tag_id = t.id
         JOIN bookmark_entity b ON bt.bookmark_id = b.id
         WHERE b.user_id = ? AND bt.delete_flag = false AND t.delete_flag = false
         GROUP BY t.id, t.name
         ORDER BY count DESC
         LIMIT 10`,
        [userId],
      );

    const mostUsedTags = mostUsedResult.map((row: any) => ({
      tagId: row.tag_id,
      tagName: row.tag_name,
      count: parseInt(row.count, 10),
    }));

    return {
      totalAssignments,
      autoGenerated,
      manuallyAdded,
      averageTagsPerBookmark,
      mostUsedTags,
    };
  }

  /**
   * Find bookmarks with multiple tags (AND operation)
   */
  async findBookmarksWithAllTags(
    tagIds: string[],
    userId: string,
  ): Promise<string[]> {
    if (tagIds.length === 0) return [];

    const result = await this.getEntityManager()
      .getConnection()
      .execute(
        `SELECT bt.bookmark_id
         FROM bookmark_tag_entity bt
         JOIN bookmark_entity b ON bt.bookmark_id = b.id
         WHERE bt.tag_id = ANY(?) 
           AND b.user_id = ? 
           AND bt.delete_flag = false 
           AND b.delete_flag = false
         GROUP BY bt.bookmark_id
         HAVING COUNT(DISTINCT bt.tag_id) = ?`,
        [tagIds, userId, tagIds.length],
      );

    return result.map((row: any) => row.bookmark_id);
  }

  /**
   * Find bookmarks with any of the tags (OR operation)
   */
  async findBookmarksWithAnyTags(
    tagIds: string[],
    userId: string,
  ): Promise<string[]> {
    if (tagIds.length === 0) return [];

    const result = await this.getEntityManager()
      .getConnection()
      .execute(
        `SELECT DISTINCT bt.bookmark_id
         FROM bookmark_tag_entity bt
         JOIN bookmark_entity b ON bt.bookmark_id = b.id
         WHERE bt.tag_id = ANY(?) 
           AND b.user_id = ? 
           AND bt.delete_flag = false 
           AND b.delete_flag = false`,
        [tagIds, userId],
      );

    return result.map((row: any) => row.bookmark_id);
  }

  /**
   * Bulk delete bookmark tags
   */
  async bulkDeleteByBookmarkIds(bookmarkIds: string[]): Promise<number> {
    if (bookmarkIds.length === 0) return 0;

    const result = await this.getEntityManager()
      .getConnection()
      .execute(
        `UPDATE bookmark_tag_entity 
         SET delete_flag = true, deleted_at = NOW() 
         WHERE bookmark_id = ANY(?) AND delete_flag = false`,
        [bookmarkIds],
      );

    return result['affectedRows'] || 0;
  }

  /**
   * Bulk delete bookmark tags by tag IDs
   */
  async bulkDeleteByTagIds(tagIds: string[]): Promise<number> {
    if (tagIds.length === 0) return 0;

    const result = await this.getEntityManager()
      .getConnection()
      .execute(
        `UPDATE bookmark_tag_entity 
         SET delete_flag = true, deleted_at = NOW() 
         WHERE tag_id = ANY(?) AND delete_flag = false`,
        [tagIds],
      );

    return result['affectedRows'] || 0;
  }

  /**
   * Find related tags (tags that appear together frequently)
   */
  async findRelatedTags(
    tagId: string,
    userId: string,
    limit: number = 10,
  ): Promise<{ tagId: string; tagName: string; coOccurrence: number }[]> {
    const result = await this.getEntityManager()
      .getConnection()
      .execute(
        `SELECT t.id as tag_id, t.name as tag_name, COUNT(*) as co_occurrence
         FROM bookmark_tag_entity bt1
         JOIN bookmark_tag_entity bt2 ON bt1.bookmark_id = bt2.bookmark_id
         JOIN tag_entity t ON bt2.tag_id = t.id
         JOIN bookmark_entity b ON bt1.bookmark_id = b.id
         WHERE bt1.tag_id = ? 
           AND bt2.tag_id != ? 
           AND b.user_id = ?
           AND bt1.delete_flag = false 
           AND bt2.delete_flag = false 
           AND t.delete_flag = false
         GROUP BY t.id, t.name
         ORDER BY co_occurrence DESC
         LIMIT ?`,
        [tagId, tagId, userId, limit],
      );

    return result.map((row: any) => ({
      tagId: row.tag_id,
      tagName: row.tag_name,
      coOccurrence: parseInt(row.co_occurrence, 10),
    }));
  }

  /**
   * Get tag timeline (when tags were added over time)
   */
  async getTagTimeline(
    userId: string,
    days: number = 30,
  ): Promise<{ date: string; count: number }[]> {
    const result = await this.getEntityManager()
      .getConnection()
      .execute(
        `SELECT DATE(bt.create_at) as date, COUNT(*) as count
         FROM bookmark_tag_entity bt
         JOIN bookmark_entity b ON bt.bookmark_id = b.id
         WHERE b.user_id = ? 
           AND bt.create_at >= NOW() - INTERVAL '? days'
           AND bt.delete_flag = false
         GROUP BY DATE(bt.create_at)
         ORDER BY date DESC`,
        [userId, days],
      );

    return result.map((row: any) => ({
      date: row.date,
      count: parseInt(row.count, 10),
    }));
  }
}
