import { BookmarkTagRepository } from '@app/repositories';
import {
  Entity,
  EntityRepositoryType,
  Index,
  ManyToOne,
  Property,
  Unique,
} from '@mikro-orm/core';
import { BaseEntity } from './base.entity';
import { BookmarkEntity } from './bookmark.entity';
import { TagEntity } from './tag.entity';
import { UserEntity } from './user.entity';

@Entity({ repository: () => BookmarkTagRepository })
@Index({ properties: ['id'] })
@Index({ properties: ['bookmark'] })
@Index({ properties: ['tag'] })
@Index({ properties: ['addedBy'] })
@Unique({ properties: ['bookmark', 'tag'] }) // Prevent duplicate tag assignments
export class BookmarkTagEntity extends BaseEntity {
  @ManyToOne(() => BookmarkEntity, { deleteRule: 'cascade' })
  bookmark: BookmarkEntity;

  @ManyToOne(() => TagEntity, { deleteRule: 'cascade' })
  tag: TagEntity;

  @ManyToOne(() => UserEntity)
  addedBy: UserEntity;

  @Property({ nullable: true, length: 500 })
  notes?: string; // Optional notes about why this tag was added

  @Property({ default: false })
  isAutoGenerated: boolean = false; // Whether tag was auto-generated

  @Property({ nullable: true })
  confidence?: number; // Confidence score for auto-generated tags (0-1)

  [EntityRepositoryType]?: BookmarkTagRepository;

  constructor({
    bookmark,
    tag,
    addedBy,
    notes,
    isAutoGenerated = false,
    confidence,
  }: {
    bookmark: BookmarkEntity;
    tag: TagEntity;
    addedBy: UserEntity;
    notes?: string;
    isAutoGenerated?: boolean;
    confidence?: number;
  }) {
    super();
    this.bookmark = bookmark;
    this.tag = tag;
    this.addedBy = addedBy;
    this.notes = notes;
    this.isAutoGenerated = isAutoGenerated;
    this.confidence = confidence;
  }

  /**
   * Check if this is a high-confidence auto-generated tag
   */
  isHighConfidence(): boolean {
    return this.isAutoGenerated && (this.confidence || 0) >= 0.8;
  }

  /**
   * Check if this tag assignment can be removed
   */
  canBeRemoved(userId: string): boolean {
    return this.addedBy.id === userId || !this.isAutoGenerated;
  }

  /**
   * Get tag assignment summary
   */
  getSummary(): {
    id: string;
    tagId: string;
    tagName: string;
    bookmarkId: string;
    addedBy: string;
    notes?: string;
    isAutoGenerated: boolean;
    confidence?: number;
    createdAt: Date;
  } {
    return {
      id: this.id,
      tagId: this.tag.id,
      tagName: this.tag.name,
      bookmarkId: this.bookmark.id,
      addedBy: this.addedBy.id,
      notes: this.notes,
      isAutoGenerated: this.isAutoGenerated,
      confidence: this.confidence,
      createdAt: this.createAt!,
    };
  }
}
