import { NumberField } from '@app/decorators';
import { ApiProperty } from '@nestjs/swagger';

export class TagStatsDto {
  @NumberField({
    description: 'Total number of tags',
    example: 50,
    int: true,
    min: 0,
  })
  total: number;

  @NumberField({
    description: 'Number of active tags',
    example: 45,
    int: true,
    min: 0,
  })
  active: number;

  @NumberField({
    description: 'Number of inactive tags',
    example: 5,
    int: true,
    min: 0,
  })
  inactive: number;

  @NumberField({
    description: 'Number of unused tags',
    example: 10,
    int: true,
    min: 0,
  })
  unused: number;

  @NumberField({
    description: 'Total usage count across all tags',
    example: 250,
    int: true,
    min: 0,
  })
  totalUsage: number;

  @ApiProperty({
    description: 'Categories with their counts',
    example: [
      { category: 'Technology', count: 15 },
      { category: 'Business', count: 10 },
    ],
    type: 'array',
    items: {
      type: 'object',
      properties: {
        category: { type: 'string' },
        count: { type: 'number' },
      },
    },
  })
  categories: { category: string; count: number }[];
}

export class TagUsageStatsDto {
  @NumberField({
    description: 'Total tag assignments',
    example: 150,
    int: true,
    min: 0,
  })
  totalAssignments: number;

  @NumberField({
    description: 'Number of auto-generated tag assignments',
    example: 50,
    int: true,
    min: 0,
  })
  autoGenerated: number;

  @NumberField({
    description: 'Number of manually added tag assignments',
    example: 100,
    int: true,
    min: 0,
  })
  manuallyAdded: number;

  @NumberField({
    description: 'Average number of tags per bookmark',
    example: 2.5,
    min: 0,
  })
  averageTagsPerBookmark: number;

  @ApiProperty({
    description: 'Most used tags',
    example: [
      { tagId: '123', tagName: 'web', count: 25 },
      { tagId: '456', tagName: 'development', count: 20 },
    ],
    type: 'array',
    items: {
      type: 'object',
      properties: {
        tagId: { type: 'string' },
        tagName: { type: 'string' },
        count: { type: 'number' },
      },
    },
  })
  mostUsedTags: { tagId: string; tagName: string; count: number }[];
}
